In [2]:
import pandas as pd

## Conditional formatting or Filtering

In [ ]:
# Syntax :-
# df[col] - condition - boolean def
# df[df[col] - condition] - filter the df

In [2]:

name = ["Ram", "john", "Abdul", "Siva", "Adam", "Rahman"]
maths = [45, 40, 60, 80, 90, 75]
english = [60, 75, 90, 65, 80, 60]

di = {
    'names': name,
    'Maths': maths,
    'English': english
}

scores_df = pd.DataFrame(di)
print(scores_df)

    names  Maths  English
0     Ram     45       60
1    john     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [3]:
scores_df['Maths']>60

0    False
1    False
2    False
3     True
4     True
5     True
Name: Maths, dtype: bool

In [5]:
scores_df[scores_df['Maths']>60]

    names  Maths  English
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [6]:
scores_df['English']>=60

0    True
1    True
2    True
3    True
4    True
5    True
Name: English, dtype: bool

In [7]:
scores_df[scores_df['English']>60]

   names  Maths  English
1   john     40       75
2  Abdul     60       90
3   Siva     80       65
4   Adam     90       80

In [ ]:
# Syntax :-

# df[(condition1)logicalsymbol(cond2)]
# only logical symbol needs to be used 
# each cond needs to be separated by brackets

In [11]:
scores_df[scores_df['English']>60][["names","Maths"]]

   names  Maths
1   john     40
2  Abdul     60
3   Siva     80
4   Adam     90

In [13]:
scores_df[(scores_df['Maths']>=60) & (scores_df['English']>=70)]

   names  Maths  English
2  Abdul     60       90
4   Adam     90       80

In [14]:
scores_df[(scores_df['Maths']>=60) & (scores_df['English']>=70)][["names","Maths"]]

   names  Maths
2  Abdul     60
4   Adam     90

In [16]:
scores_df[(scores_df['Maths']>=60) & (scores_df['English']>=70)][["names","English"]]

   names  English
2  Abdul       90
4   Adam       80

In [17]:
scores_df[(scores_df["Maths"]>=60)|(scores_df["English"]>=70)]

    names  Maths  English
1    john     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [20]:
scores_df[scores_df["names"]=="john"]

  names  Maths  English
1  john     40       75

In [22]:
scores_df[scores_df["names"]=="john"][["names","English"]]

  names  English
1  john       75

In [21]:
scores_df[scores_df["names"]!="john"]

    names  Maths  English
0     Ram     45       60
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [2]:
names = ['A','B','C','D','E']
phy = [70,72,75,80,81]
mat = [65,70,90,74,81]
di = {'names':names,"Physics":phy,"Maths":mat}
scores_df = pd.DataFrame(di)
scores_df

  names  Physics  Maths
0     A       70     65
1     B       72     70
2     C       75     90
3     D       80     74
4     E       81     81

In [4]:
scores_df[(scores_df["Maths"]>72)&(scores_df["Physics"]>70)]

  names  Physics  Maths
2     C       75     90
3     D       80     74
4     E       81     81

In [8]:
scores_df[(scores_df["Maths"]<60)&(scores_df["Physics"]<72)]["names"]

Series([], Name: names, dtype: str)

## Adding and replacing columns

In [9]:

name = ["Ram", "john", "Abdul", "Siva", "Adam", "Rahman"]
maths = [45, 40, 60, 80, 90, 75]
english = [60, 75, 90, 65, 80, 60]

di = {
    'names': name,
    'Maths': maths,
    'English': english
}

scores_df = pd.DataFrame(di)
print(scores_df)

    names  Maths  English
0     Ram     45       60
1    john     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [ ]:
# Syntax :-

# df["new column name"]=[values]

In [10]:
scores_df["Science"]=[54,65,89,77,56,92]

In [11]:
scores_df

    names  Maths  English  Science
0     Ram     45       60       54
1    john     40       75       65
2   Abdul     60       90       89
3    Siva     80       65       77
4    Adam     90       80       56
5  Rahman     75       60       92

In [12]:
# Syntax:-

# df["existing column name"]=[values]

In [13]:
scores_df["Science"]=[56,77,43,68,89,95]
scores_df

    names  Maths  English  Science
0     Ram     45       60       56
1    john     40       75       77
2   Abdul     60       90       43
3    Siva     80       65       68
4    Adam     90       80       89
5  Rahman     75       60       95

## Adding and replacing row

In [14]:
# Syntax:-

# df_name.loc[new index]= row wise list

In [17]:
scores_df.loc[6] = ["Akbar",87,67,90]
scores_df

    names  Maths  English  Science
0     Ram     45       60       56
1    john     40       75       77
2   Abdul     60       90       43
3    Siva     80       65       68
4    Adam     90       80       89
5  Rahman     75       60       95
6   Akbar     87       67       90

In [18]:
scores_df.iloc[6]

names      Akbar
Maths         87
English       67
Science       90
Name: 6, dtype: object

In [19]:
scores_df.iloc[6]=["Mohamed",90,75,92]

In [20]:
scores_df

     names  Maths  English  Science
0      Ram     45       60       56
1     john     40       75       77
2    Abdul     60       90       43
3     Siva     80       65       68
4     Adam     90       80       89
5   Rahman     75       60       95
6  Mohamed     90       75       92

In [22]:
scores_df.loc[3,"Science"]

np.int64(68)

In [25]:
# Syntax :-
# df_name[row index , col index] = new value

In [23]:
scores_df.loc[3,"Science"]= [70]

In [24]:
scores_df

     names  Maths  English  Science
0      Ram     45       60       56
1     john     40       75       77
2    Abdul     60       90       43
3     Siva     80       65       70
4     Adam     90       80       89
5   Rahman     75       60       95
6  Mohamed     90       75       92

In [ ]:
# Syntax :-

# df['colname'].replace({oldvalue:newvalue},inplace = T/F) # To replace in the
# df['rowname'].replace

In [28]:
scores_df['English'].replace({60:70},inplace = True)
scores_df

/var/folders/fm/t_0d_0s533j69c8m_k2xl4300000gn/T/ipykernel_64397/38668385.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  scores_df['English'].replace({60:70},inplace = True)

     names  Maths  English  Science
0      Ram     45       60       56
1     john     40       75       77
2    Abdul     60       90       43
3     Siva     80       65       70
4     Adam     90       80       89
5   Rahman     75       60       95
6  Mohamed     90       75       92

In [27]:
scores_df

     names  Maths  English  Science
0      Ram     45       60       56
1     john     40       75       77
2    Abdul     60       90       43
3     Siva     80       65       70
4     Adam     90       80       89
5   Rahman     75       60       95
6  Mohamed     90       75       92

In [33]:
scores_df.replace({75:80,70:80},inplace=True)

     names  Maths  English  Science
0      Ram     45       60       56
1     john     40       80       77
2    Abdul     60       90       43
3     Siva     80       65       80
4     Adam     90       80       89
5   Rahman     80       60       95
6  Mohamed     90       80       92

In [12]:
import pandas as pd


name = ["Ram", "john", "Abdul", "Siva", "Adam", "Rahman"]
maths = [45, 40, 60, 80, 90, 75]
english = [60, 75, 90, 65, 80, 60]

di = {
    'names': name,
    'Maths': maths,
    'English': english
}

scores_df = pd.DataFrame(di)
print(scores_df)

    names  Maths  English
0     Ram     45       60
1    john     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [ ]:
# Syntax :-

# df['colname'] = df['colname'].replace({oldvalue:newvalue}) # To replace in the
# df['rowname'] = df['rowname'].replace({oldvalue:newvalue})

In [ ]:
scores_df['Maths'] = scores_df['Maths'].replace({40:42}) # Replace maths column 40 to 42
scores_df

    names  Maths  English
0     Ram     45       60
1    john     42       75
2   Abdul     60       90
3    Siva     80       67
4    Adam     90       80
5  Rahman     75       60

In [ ]:
scores_df['English']= scores_df['English'].replace({65:67}) # replace English column 65 to 67
scores_df

    names  Maths  English
0     Ram     45       60
1    john     42       75
2   Abdul     60       90
3    Siva     80       67
4    Adam     90       80
5  Rahman     75       60

In [28]:
scores_df

    names  Maths  English
0     Ram     45       60
1    john     42       75
2   Abdul     60       90
3    Siva     80       67
4    Adam     90       80
5  Rahman     75       60

In [30]:
scores_df.replace({75:77},inplace= True)
scores_df

    names  Maths  English
0     Ram     45       60
1    john     42       77
2   Abdul     60       90
3    Siva     80       67
4    Adam     90       80
5  Rahman     77       60

In [31]:
scores_df.loc[3,"English"]= [70]

In [32]:
scores_df

    names  Maths  English
0     Ram     45       60
1    john     42       77
2   Abdul     60       90
3    Siva     80       70
4    Adam     90       80
5  Rahman     77       60

In [ ]:
# syntax:

# dataframe.rename({'oldname':'newname'})

# index - renaming the index

# column - renaming the column

# axis - 0,1

# inplace - to save te change by default inplace=False

In [3]:
mark = {'Student_name':['A','B','C','D','E','F'],

        'Marks' : [70,80,90,100,100,70],

        'class':[8,8,9,9,10,10]}

df_mark = pd.DataFrame(mark)

df_mark

  Student_name  Marks  class
0            A     70      8
1            B     80      8
2            C     90      9
3            D    100      9
4            E    100     10
5            F     70     10

In [4]:
df_mark.rename({'Student_name':'Name'},axis=1,inplace=True)

In [5]:
df_mark

  Name  Marks  class
0    A     70      8
1    B     80      8
2    C     90      9
3    D    100      9
4    E    100     10
5    F     70     10

In [6]:
df_mark.rename({4:40,5:50},axis = 0,inplace=True)
df_mark

   Name  Marks  class
0     A     70      8
1     B     80      8
2     C     90      9
3     D    100      9
40    E    100     10
50    F     70     10

In [31]:
df_mark

   Student_name  Marks  class
0             A     70      8
1             B     80      8
2             C     90      9
3             D    100      9
40            E    100     10
50            F     70     10

In [7]:
df_mark.drop("class",axis=1)

   Name  Marks
0     A     70
1     B     80
2     C     90
3     D    100
40    E    100
50    F     70

In [8]:
df_mark.drop([40,50],axis=0,inplace=True)

In [9]:
df_mark

  Name  Marks  class
0    A     70      8
1    B     80      8
2    C     90      9
3    D    100      9

In [33]:
# Sorting

scores_df

    names  Maths  English
0     Ram     45       60
1    john     42       77
2   Abdul     60       90
3    Siva     80       70
4    Adam     90       80
5  Rahman     77       60

In [34]:
scores_df.sort_values(by ="English") # ascending order

    names  Maths  English
0     Ram     45       60
5  Rahman     77       60
3    Siva     80       70
1    john     42       77
4    Adam     90       80
2   Abdul     60       90

In [ ]:
scores_df.sort_values(by ="English",ascending=False) # desending order

    names  Maths  English
2   Abdul     60       90
4    Adam     90       80
1    john     40       75
3    Siva     80       65
0     Ram     45       60
5  Rahman     75       60

## How to sort Multiple Values..??

In [35]:
scores_df.sort_values(by =["Maths","English"],ascending=[False,False])

    names  Maths  English
4    Adam     90       80
3    Siva     80       70
5  Rahman     77       60
2   Abdul     60       90
0     Ram     45       60
1    john     42       77

In [19]:
scores_df.sort_values(by =["Maths","English"],ascending=[False,True])

    names  Maths  English
4    Adam     90       80
3    Siva     80       65
5  Rahman     75       60
2   Abdul     60       90
0     Ram     45       60
1    john     40       75

In [25]:
scores_df.loc[scores_df["Maths"].idxmax()]

names      Adam
Maths        90
English      80
Name: 4, dtype: object

In [48]:
import numpy as np
a = np.array([11,21,12,13,14],ndmin=2)
print(a)
np.ndim(a)
print(np.cumsum(a))

[[11 21 12 13 14]]
[11 32 44 57 71]