# Introduction to Data Frame
## Data Frame

- creating Dataframe

In [1]:
# key = col_names
# list of values = elements of each column
# Syntax :
# data_frame_name = pd.DataFrame(dictionary/list of list,index(opt),columns(opt))

In [2]:
import pandas as pd

In [3]:
emp_data = pd.DataFrame({"emp_id":[101,102,103,104,105],
              "name":["suriya","john","doe","paul","karthick"],
              "dept":["AIML","ML","DA","DS","PD"],
              "salary":[20,30,24,45,50]})
emp_data

   emp_id      name  dept  salary
0     101    suriya  AIML      20
1     102      john    ML      30
2     103       doe    DA      24
3     104      paul    DS      45
4     105  karthick    PD      50

In [7]:
emp_id = pd.Series([101,102,103,104,105])
name = pd.Series(["suriya","john","doe","paul","karthick"])
dept = pd.Series(["AIML","ML","DA","DS","PD"])
salary = pd.Series([20,30,24,45,50])

pd.DataFrame([emp_id,name,dept,salary],index=['emp_id','name','dept','salary']).T

  emp_id      name  dept salary
0    101    suriya  AIML     20
1    102      john    ML     30
2    103       doe    DA     24
3    104      paul    DS     45
4    105  karthick    PD     50

In [9]:
emp_id = pd.Series([101,102,103,104,105])
name = pd.Series(["suriya","john","doe","paul","karthick"])
dept = pd.Series(["AIML","ML","DA","DS","PD"])
salary = pd.Series([20,30,24,45,50])

pd.DataFrame([emp_id,name,dept,salary],index=['emp_id','emp_name','dept','salary'])

               0     1    2     3         4
emp_id       101   102  103   104       105
emp_name  suriya  john  doe  paul  karthick
dept        AIML    ML   DA    DS        PD
salary        20    30   24    45        50

In [10]:
id = [101,102,103,104,105]
name = ["suriya","john","doe","paul","karthick"]
dept = ["AIML","ML","DA","DS","PD"]
salary = [20,30,24,45,50]

pd.DataFrame({"emp_id":id,"emp_name":name,"dept":dept,"Salary":salary})

   emp_id  emp_name  dept  Salary
0     101    suriya  AIML      20
1     102      john    ML      30
2     103       doe    DA      24
3     104      paul    DS      45
4     105  karthick    PD      50

In [11]:
pd.DataFrame([[101,"suriya","AIML",20],[102,"john","ML",30],[103,"doe","DA",24]],columns = ["emp_id","name","dept","salary"])

   emp_id    name  dept  salary
0     101  suriya  AIML      20
1     102    john    ML      30
2     103     doe    DA      24

In [12]:
# Creating a dictionary for dataframe

# Syntax : di_name = {'colname 1':list of elements in column1 , 'colname 2':list of elements in column2}

In [13]:
# practice
emp_data = pd.DataFrame({
              "name":["Ram","john","Abdul","Siva","Adam","Rahman"],
              "maths":[45,40,60,80,90,75],
              "english":[60,75,90,65,80,60]})
emp_data

     name  maths  english
0     Ram     45       60
1    john     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [ ]:
# Column wise
name = ["Ram","john","Abdul","Siva","Adam","Rahman"]
maths = [45,40,60,80,90,75]
english = [60,75,90,65,80,60]

scores_df = pd.DataFrame({"student_name":name,"maths_marks":maths,"English_marks":english})
scores_df

  student_name  maths_marks  English_marks
0          Ram           45             60
1         john           40             75
2        Abdul           60             90
3         Siva           80             65
4         Adam           90             80
5       Rahman           75             60

In [17]:
# list of list Row wise
scores_df = pd.DataFrame([["Ram",45,60],
                          ["john",40,75],
                          ["Abdul",60,90],
                          ["Siva",80,65],
                          ["Adam",90,80],
                          ["Rahman",75,60]],
                         columns = ["Student_name","Maths_marks","English_marks"])
scores_df

  Student_name  Maths_marks  English_marks
0          Ram           45             60
1         john           40             75
2        Abdul           60             90
3         Siva           80             65
4         Adam           90             80
5       Rahman           75             60

In [18]:
scores_df.shape

(6, 3)

In [29]:
# Head and Tail
scores_df.head() # By default it will take the first 5 rows

  Student_name  Maths_marks  English_marks
0          Ram           45             60
1         john           40             75
2        Abdul           60             90
3         Siva           80             65
4         Adam           90             80

In [30]:
scores_df.head(3)

  Student_name  Maths_marks  English_marks
0          Ram           45             60
1         john           40             75
2        Abdul           60             90

In [31]:
scores_df.tail() # By default it will take the last 5 rows

  Student_name  Maths_marks  English_marks
1         john           40             75
2        Abdul           60             90
3         Siva           80             65
4         Adam           90             80
5       Rahman           75             60

In [32]:
scores_df.tail(3)

  Student_name  Maths_marks  English_marks
3         Siva           80             65
4         Adam           90             80
5       Rahman           75             60

In [34]:
# practice
scores_df = pd.DataFrame({"Student_name":['A','B','C','D','E','F'],
                          "Marks":[70,80,90,100,100,70],
                          "class":[8,8,9,10,10,10]})
scores_df

  Student_name  Marks  class
0            A     70      8
1            B     80      8
2            C     90      9
3            D    100     10
4            E    100     10
5            F     70     10

In [35]:
scores_df.head(3)

  Student_name  Marks  class
0            A     70      8
1            B     80      8
2            C     90      9

In [36]:
scores_df.tail(3)

  Student_name  Marks  class
3            D    100     10
4            E    100     10
5            F     70     10

## DataFrame Indexing and Slicing

In [37]:
scores_df['Student_name']

0    A
1    B
2    C
3    D
4    E
5    F
Name: Student_name, dtype: str

In [38]:
scores_df['Student_name'][3]

'D'

- iloc =  index location

In [40]:
# Syntax:-
# df_name.iloc[row_index,col_index]

scores_df.iloc[0,0]

'A'

In [41]:
scores_df.iloc[1,0]

'B'

In [42]:
scores_df.iloc[2,0]

'C'

In [43]:
scores_df.iloc[2,2]

np.int64(9)

In [ ]:
scores_df.iloc[[0,3,5],[0,1,2]] # .iloc[[row],[col]]

  Student_name  Marks  class
0            A     70      8
3            D    100     10
5            F     70     10

In [55]:
# slicing

scores_df.iloc[2:5:2,0:3:1] # .iloc[row:row:step,col:col:step]

  Student_name  Marks  class
2            C     90      9
4            E    100     10

In [58]:

scores_df.iloc[0:,0:3:1]  # Even rows

  Student_name  Marks  class
0            A     70      8
1            B     80      8
2            C     90      9
3            D    100     10
4            E    100     10
5            F     70     10

In [60]:
scores_df.iloc[::2,::2]

  Student_name  class
0            A      8
2            C      9
4            E     10

In [61]:
scores_df.iloc[::2,:]

  Student_name  Marks  class
0            A     70      8
2            C     90      9
4            E    100     10

In [62]:
scores_df.iloc[:,::2]

  Student_name  class
0            A      8
1            B      8
2            C      9
3            D     10
4            E     10
5            F     10

In [63]:
# list of list Row wise
scores_df = pd.DataFrame([["Ram",45,60],
                          ["john",40,75],
                          ["Abdul",60,90],
                          ["Siva",80,65],
                          ["Adam",90,80],
                          ["Rahman",75,60]],
                         columns = ["Student_name","Maths_marks","English_marks"])
scores_df

  Student_name  Maths_marks  English_marks
0          Ram           45             60
1         john           40             75
2        Abdul           60             90
3         Siva           80             65
4         Adam           90             80
5       Rahman           75             60

In [72]:
# practice


name = ["Ram", "john", "Abdul", "Siva", "Adam", "Rahman"]
maths = [45, 40, 60, 80, 90, 75]
english = [60, 75, 90, 65, 80, 60]

di = {
    'names': name,
    'Maths': maths,
    'English': english
}

scores_df = pd.DataFrame(di)
print(scores_df)

    names  Maths  English
0     Ram     45       60
1    john     40       75
2   Abdul     60       90
3    Siva     80       65
4    Adam     90       80
5  Rahman     75       60

In [74]:
print(scores_df.iloc[1,1])

40

In [75]:
print(scores_df.iloc[[1,2,3],[1]])

   Maths
1     40
2     60
3     80

In [76]:
print(scores_df.iloc[[1,3,4],[1,2]])

   Maths  English
1     40       75
3     80       65
4     90       80

- loc = name based indexing

In [78]:
# Syntax:-
# df_name.loc[indexname,columnname]

scores_df.loc[0,"names"]

'Ram'

In [81]:
print(scores_df.loc[0,"Maths"])

45

In [82]:
print(scores_df.loc[0,"English"])

60

In [83]:
print(scores_df.loc[[0,1,4],["names","Maths","English"]])

  names  Maths  English
0   Ram     45       60
1  john     40       75
4  Adam     90       80

In [ ]:
# slicing. here the (name type) value in included
print(scores_df.loc[0:4:1,"names":"Maths"])

   names  Maths
0    Ram     45
1   john     40
2  Abdul     60
3   Siva     80
4   Adam     90

In [ ]:
# Mixed Indexing and slicing
print(scores_df.loc[0:4:1,["names","English"]])

   names  English
0    Ram       60
1   john       75
2  Abdul       90
3   Siva       65
4   Adam       80

## Column slicing

In [87]:
# Syntax :- df_name[colname]

scores_df["names"]

0       Ram
1      john
2     Abdul
3      Siva
4      Adam
5    Rahman
Name: names, dtype: str

In [88]:
scores_df[["names","English"]]

    names  English
0     Ram       60
1    john       75
2   Abdul       90
3    Siva       65
4    Adam       80
5  Rahman       60

In [89]:
# Practice
print(scores_df.loc[1,"Maths"])

40

In [90]:
print(scores_df.loc[[1,2,3],"Maths"])

1    40
2    60
3    80
Name: Maths, dtype: int64

In [91]:
print(scores_df.loc[[1,3,4],["Maths","English"]])

   Maths  English
1     40       75
3     80       65
4     90       80

In [92]:
print(scores_df["Maths"])

0    45
1    40
2    60
3    80
4    90
5    75
Name: Maths, dtype: int64

In [5]:
n = 4

for i in range(1, n + 1):
    print(" " * (n - i), end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    print()

   1
  1 2
 1 2 3
1 2 3 4