## DATASET : READ ANALYZE EXPLORER

In [6]:
import pandas as pd

## READING DATA FROM DIFFERENT SOURCES
- 1) CSV = pd.read_csv("train.csv")
- 2) EXCEL = pd.read_xlse("train.excel")
- 3) JSON file = pd.read_json("train.json")

In [2]:
# Syntax :-
# \ - /
emp1 = pd.read_csv("/Users/vijaypatil/Desktop/Innomatics/EDA/datasets/people.csv")
emp1

    Age  Gender   Hometown  Height  Qualification Smoker
0    45    Male     Mumbai     167       Graduate    Yes
1    23  Female     Mumbai     170       Graduate     No
2    27    Male     Mumbai     175  Post-graduate     No
3    34    Male      Delhi     155       Graduate     No
4    43  Female     Mumbai     157  Post-graduate    Yes
5    34    Male      Delhi     167        Diploma    Yes
6    44  Female     Mumbai     165       Graduate    Yes
7    56  Female      Delhi     170        Diploma    Yes
8    34    Male      Delhi     175  Post-graduate     No
9    49  Female  Bangalore     162  Post-graduate    Yes
10   35    Male  Bangalore     160       Graduate     No
11   28  Female     Mumbai     165        Diploma     No
12   54    Male      Delhi     170        Diploma    Yes
13   59  Female     Mumbai     175       Graduate     No
14   54    Male  Bangalore     175        Diploma    Yes
15   43  Female     Mumbai     155  Post-graduate     No
16   56  Female     Mumbai     151       Graduate     No
17   41    Male  Bangalore     180        Diploma     No
18   56    Male      Delhi     182       Graduate    Yes
19   53    Male  Bangalore     156  Post-graduate    Yes
20   21  Female  Bangalore     158  Post-graduate     No

In [7]:
pd.read_csv("datasets/people.csv")

    Age  Gender   Hometown  Height  Qualification Smoker
0    45    Male     Mumbai     167       Graduate    Yes
1    23  Female     Mumbai     170       Graduate     No
2    27    Male     Mumbai     175  Post-graduate     No
3    34    Male      Delhi     155       Graduate     No
4    43  Female     Mumbai     157  Post-graduate    Yes
5    34    Male      Delhi     167        Diploma    Yes
6    44  Female     Mumbai     165       Graduate    Yes
7    56  Female      Delhi     170        Diploma    Yes
8    34    Male      Delhi     175  Post-graduate     No
9    49  Female  Bangalore     162  Post-graduate    Yes
10   35    Male  Bangalore     160       Graduate     No
11   28  Female     Mumbai     165        Diploma     No
12   54    Male      Delhi     170        Diploma    Yes
13   59  Female     Mumbai     175       Graduate     No
14   54    Male  Bangalore     175        Diploma    Yes
15   43  Female     Mumbai     155  Post-graduate     No
16   56  Female     Mumbai     151       Graduate     No
17   41    Male  Bangalore     180        Diploma     No
18   56    Male      Delhi     182       Graduate    Yes
19   53    Male  Bangalore     156  Post-graduate    Yes
20   21  Female  Bangalore     158  Post-graduate     No

In [ ]:
# read a.xlsx file
import pandas as pd

Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/anaconda3/lib/python3.12/site-packages (from openpyxl) (1.1.0)

In [5]:
employee = pd.read_excel("/Users/vijaypatil/Desktop/Innomatics/EDA/datasets/employee_info.xlsx")
employee

   Age  Gender  Salary
0   45    Male   40000
1   12    Male       0
2   54  Female  150000
3   26    Male   30000
4   64  Female   15000
5   21  Female   25600

In [ ]:
#  read a.json file
pd.read_json("/Users/vijaypatil/Desktop/Innomatics/EDA/datasets/iris.json")

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [9]:
input = pd.read_csv("datasets/Input.csv")
input

    Empid     Name      Dept Gender     City  Salary
0       1   Samuel     Admin      M  Chennai   45000
1       2    Jerry        IT      M    Blore   75000
2       3  Michale     Sales      F      Goa   30000
3       4    Joann        IT      F  Chennai   80000
4       5   Sherin        IT      F    Blore   78000
5       6  Maxwell  Networks      M  Chennai   35000
6       7     John     Sales      M  Chennai   28000
7       8     Cruz        IT      M  Chennai   89000
8       9     Mary        IT      F    Blore   65000
9      10    Merry     Sales      F    Blore   45000
10     11    Jacob        IT      M      Goa   67000
11     12      Liz        IT      F  Kolkata   65000
12     13  Saneeta  Networks      F  Kolkata   55000
13     14    Jason     Sales      M      Goa   40000
14     15     Mike        IT      M  Kolkata    8000

In [10]:
input.head()

   Empid     Name   Dept Gender     City  Salary
0      1   Samuel  Admin      M  Chennai   45000
1      2    Jerry     IT      M    Blore   75000
2      3  Michale  Sales      F      Goa   30000
3      4    Joann     IT      F  Chennai   80000
4      5   Sherin     IT      F    Blore   78000

In [12]:
input.tail(10)

    Empid     Name      Dept Gender     City  Salary
5       6  Maxwell  Networks      M  Chennai   35000
6       7     John     Sales      M  Chennai   28000
7       8     Cruz        IT      M  Chennai   89000
8       9     Mary        IT      F    Blore   65000
9      10    Merry     Sales      F    Blore   45000
10     11    Jacob        IT      M      Goa   67000
11     12      Liz        IT      F  Kolkata   65000
12     13  Saneeta  Networks      F  Kolkata   55000
13     14    Jason     Sales      M      Goa   40000
14     15     Mike        IT      M  Kolkata    8000

## Basic Operations

In [16]:
# min,max,sum,mean,std,unique,nunique

print("Minimum Salary :",input["Salary"].min())

Minimum Salary : 8000

In [15]:
print("Maximum Salary :",input["Salary"].max())

Maximum Salary : 89000

In [17]:

print("Total Salary :",input["Salary"].sum())

Total Salary : 805000

In [20]:

print("Average Salary :",input["Salary"].mean())

Average Salary : 53666.666666666664

In [19]:

print("Standard deviation :",input["Salary"].std())

Standard deviation : 23014.488190413154

In [21]:

print("Unique key :",input["Salary"].unique())

Unique key : [45000 75000 30000 80000 78000 35000 28000 89000 65000 67000 55000 40000
  8000]

In [28]:

print("Unique Department :",input["Dept"].unique())

Unique Department : <StringArray>
['Admin', 'IT', 'Sales', 'Networks']
Length: 4, dtype: str

In [26]:

print("Nu. of unique key :",input["Salary"].nunique())

Nu. of unique key : 13

In [27]:
print("Nu. of unique key :",input["Dept"].nunique())

Nu. of unique key : 4

In [8]:
print("Minimum :",emp1["Smoker"].min())
print("Nu. of count :",emp1["Smoker"].unique())
print("Nu. of count :",emp1["Smoker"].nunique())
print("Maximum :",emp1["Smoker"].max())

Minimum : No
Nu. of count : <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Nu. of count : 2
Maximum : Yes

In [9]:
# value_counts(normalize = False,sort=true,ascending=False,bins=None,dropna=True)

In [10]:
emp1['Smoker'].value_counts()

Smoker
No     11
Yes    10
Name: count, dtype: int64

In [12]:
emp1['Smoker'].value_counts(normalize=True)*100

Smoker
No     52.380952
Yes    47.619048
Name: proportion, dtype: float64

In [13]:
# non numerical column - .DS_Store

# Syntax :- df['colname].info()

In [14]:
emp1.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            21 non-null     int64
 1   Gender         21 non-null     str
 2   Hometown       21 non-null     str
 3   Height         21 non-null     int64
 4   Qualification  21 non-null     str
 5   Smoker         21 non-null     str
dtypes: int64(2), str(4)
memory usage: 1.1 KB

In [ ]:
# Summary statistics
emp1.describe()

             Age      Height
count  21.000000   21.000000
mean   42.333333  166.190476
std    11.858893    8.919748
min    21.000000  151.000000
25%    34.000000  158.000000
50%    43.000000  167.000000
75%    54.000000  175.000000
max    59.000000  182.000000

In [16]:
emp1.describe(include='all')

              Age Gender Hometown      Height Qualification Smoker
count   21.000000     21       21   21.000000            21     21
unique        NaN      2        3         NaN             3      2
top           NaN   Male   Mumbai         NaN      Graduate     No
freq          NaN     11        9         NaN             8     11
mean    42.333333    NaN      NaN  166.190476           NaN    NaN
std     11.858893    NaN      NaN    8.919748           NaN    NaN
min     21.000000    NaN      NaN  151.000000           NaN    NaN
25%     34.000000    NaN      NaN  158.000000           NaN    NaN
50%     43.000000    NaN      NaN  167.000000           NaN    NaN
75%     54.000000    NaN      NaN  175.000000           NaN    NaN
max     59.000000    NaN      NaN  182.000000           NaN    NaN

## Pivot Table

In [2]:
import pandas as pd

d = {
    'Name': ['Jony', 'Anil', 'Sunil', 'Jony', 'Anil', 'Rocky',
             'Jony', 'Anil', 'Sunil', 'Jony', 'Anil', 'Rocky'],

    'Exam_Months': ['3_Months', '3_Months', '3_Months', '3_Months', '3_Months', '3_Months',
                    '6_Months', '6_Months', '6_Months', '6_Months', '6_Months', '6_Months'],

    'Subject': ['Python', 'Python', 'SQL', 'SQL', 'ML', 'ML',
                'Python', 'Python', 'SQL', 'SQL', 'ML', 'ML'],

    'Theory': [62, 47, 55, 74, 31, 77, 85, 63, 42, 67, 89, 81],

    'Lab': [70, 60, 63, 80, 40, 77, 67, 70, 80, 90, 92, 95]
}

df = pd.DataFrame(
    d,
    columns=['Name', 'Exam_Months', 'Subject', 'Theory', 'Lab']
)

df

     Name Exam_Months Subject  Theory  Lab
0    Jony    3_Months  Python      62   70
1    Anil    3_Months  Python      47   60
2   Sunil    3_Months     SQL      55   63
3    Jony    3_Months     SQL      74   80
4    Anil    3_Months      ML      31   40
5   Rocky    3_Months      ML      77   77
6    Jony    6_Months  Python      85   67
7    Anil    6_Months  Python      63   70
8   Sunil    6_Months     SQL      42   80
9    Jony    6_Months     SQL      67   90
10   Anil    6_Months      ML      89   92
11  Rocky    6_Months      ML      81   95

In [25]:
# Syntax :-
# pd.pivot_table(dataframe,index=columns,aggfunc=np.mean)

# recommandation

# index = non-numerical column

In [26]:
# in agg_func - np.mean , np.median , np.std , np.var ,np.max , np.min

In [9]:
import numpy as np
pd.pivot_table(df,index="Subject",aggfunc = np.min)

        Exam_Months  Lab  Name  Theory
Subject
ML         3_Months   40  Anil      31
Python     3_Months   60  Anil      47
SQL        3_Months   63  Jony      42

In [28]:
pd.pivot_table(df,index="Subject",aggfunc = np.max)

        Exam_Months  Lab   Name  Theory
Subject
ML         6_Months   95  Rocky      89
Python     6_Months   70   Jony      85
SQL        6_Months   90  Sunil      74

In [29]:
pd.pivot_table(df,index="Subject",values ="Lab",aggfunc = np.mean)

           Lab
Subject
ML       76.00
Python   66.75
SQL      78.25

In [32]:
df[df["Subject"]=="Python"]["Lab"].mean()

np.float64(66.75)

In [33]:
df[df["Subject"]=="ML"]["Lab"].mean()

np.float64(76.0)

In [34]:
df[df["Subject"]=="SQL"]["Lab"].mean()

np.float64(78.25)

In [35]:
pd.pivot_table(df,index=["Subject"],values =["Lab","Theory"],aggfunc = np.mean)

           Lab  Theory
Subject
ML       76.00   69.50
Python   66.75   64.25
SQL      78.25   59.50

In [41]:
df.groupby(["Exam_Months", "Subject"])[["Lab", "Theory"]].mean()

                      Lab  Theory
Exam_Months Subject
3_Months    ML       58.5    54.0
            Python   65.0    54.5
            SQL      71.5    64.5
6_Months    ML       93.5    85.0
            Python   68.5    74.0
            SQL      85.0    54.5

In [ ]:

pd.pivot_table(df,index=["Exam_Months","Subject"],values =["Lab","Theory"],aggfunc = np.mean)

                      Lab  Theory
Exam_Months Subject
3_Months    ML       58.5    54.0
            Python   65.0    54.5
            SQL      71.5    64.5
6_Months    ML       93.5    85.0
            Python   68.5    74.0
            SQL      85.0    54.5

In [40]:
pd.pivot_table(df,index=["Exam_Months","Subject"],values =["Lab","Theory"],aggfunc = np.sum)

                     Lab  Theory
Exam_Months Subject
3_Months    ML       117     108
            Python   130     109
            SQL      143     129
6_Months    ML       187     170
            Python   137     148
            SQL      170     109

In [10]:
df.groupby(["Exam_Months","Subject"]).agg({"Lab":np.mean,"Theory":np.sum})

                      Lab  Theory
Exam_Months Subject
3_Months    ML       58.5     108
            Python   65.0     109
            SQL      71.5     129
6_Months    ML       93.5     170
            Python   68.5     148
            SQL      85.0     109

In [47]:
df.groupby(["Exam_Months","Subject"]).agg(np.sum)

                          Name  Theory  Lab
Exam_Months Subject
3_Months    ML       AnilRocky     108  117
            Python    JonyAnil     109  130
            SQL      SunilJony     129  143
6_Months    ML       AnilRocky     170  187
            Python    JonyAnil     148  137
            SQL      SunilJony     109  170

In [23]:
lab = df.groupby(["Exam_Months"]).agg({"Lab":np.mean})
lab
Th = df.groupby(["Exam_Months"]).agg({"Theory":np.mean})
Th
avg = lab*Th
print(avg)

             Lab  Theory
Exam_Months
3_Months     NaN     NaN
6_Months     NaN     NaN

In [15]:
df.groupby(["Exam_Months","Subject"]).agg({"Lab":np.mean,"Theory":np.std})

                      Lab  Theory
Exam_Months Subject
3_Months    ML       58.5    23.0
            Python   65.0     7.5
            SQL      71.5     9.5
6_Months    ML       93.5     4.0
            Python   68.5    11.0
            SQL      85.0    12.5