In [1]:
import pandas as pd

## Crosstab

In [2]:
# read the csv file
# df_people = pd.read_csv('people.csv)

# print head of the data
# df_people

In [ ]:
# Syntax :- pd.crosstab(col1,col2)

In [4]:
# read the csv file
df_people = pd.read_csv('datasets/people.csv')

In [5]:
# print head of the data
df_people

    Age  Gender   Hometown  Height  Qualification Smoker
0    45    Male     Mumbai     167       Graduate    Yes
1    23  Female     Mumbai     170       Graduate     No
2    27    Male     Mumbai     175  Post-graduate     No
3    34    Male      Delhi     155       Graduate     No
4    43  Female     Mumbai     157  Post-graduate    Yes
5    34    Male      Delhi     167        Diploma    Yes
6    44  Female     Mumbai     165       Graduate    Yes
7    56  Female      Delhi     170        Diploma    Yes
8    34    Male      Delhi     175  Post-graduate     No
9    49  Female  Bangalore     162  Post-graduate    Yes
10   35    Male  Bangalore     160       Graduate     No
11   28  Female     Mumbai     165        Diploma     No
12   54    Male      Delhi     170        Diploma    Yes
13   59  Female     Mumbai     175       Graduate     No
14   54    Male  Bangalore     175        Diploma    Yes
15   43  Female     Mumbai     155  Post-graduate     No
16   56  Female     Mumbai     151       Graduate     No
17   41    Male  Bangalore     180        Diploma     No
18   56    Male      Delhi     182       Graduate    Yes
19   53    Male  Bangalore     156  Post-graduate    Yes
20   21  Female  Bangalore     158  Post-graduate     No

In [9]:
pd.crosstab(df_people["Gender"],df_people["Smoker"])

Smoker  No  Yes
Gender
Female   6    4
Male     5    6

In [10]:
pd.crosstab(df_people["Hometown"],df_people["Qualification"])

Qualification  Diploma  Graduate  Post-graduate
Hometown
Bangalore            2         1              3
Delhi                3         2              1
Mumbai               1         5              3

In [11]:
pd.crosstab(df_people["Qualification"],df_people["Smoker"])

Smoker         No  Yes
Qualification
Diploma         2    4
Graduate        5    3
Post-graduate   4    3

In [12]:
pd.crosstab(df_people["Gender"],df_people["Hometown"])

Hometown  Bangalore  Delhi  Mumbai
Gender
Female            2      1       7
Male              4      5       2

## Duplicates

In [19]:
import pandas as pd

d = {
    'Name': ['Jony', 'Anil', 'Sunil', 'Jony', 'Anil', 'Rocky',
             'Jony', 'Anil', 'Sunil', 'Jony', 'Anil', 'Rocky'],

    'Exam_Months': ['3_Months', '3_Months', '3_Months', '3_Months', '3_Months', '3_Months',
                    '6_Months', '6_Months', '6_Months', '6_Months', '6_Months', '6_Months'],

    'Subject': ['Python', 'Python', 'SQL', 'SQL', 'ML', 'ML',
                'Python', 'Python', 'SQL', 'SQL', 'ML', 'ML'],

    'score':[62,47,42,74,31,77,62,63,42,67,89,81]
}

df = pd.DataFrame(
    d,
    columns=['Name', 'Exam_Months', 'Subject', 'score']
)

df

     Name Exam_Months Subject  score
0    Jony    3_Months  Python     62
1    Anil    3_Months  Python     47
2   Sunil    3_Months     SQL     42
3    Jony    3_Months     SQL     74
4    Anil    3_Months      ML     31
5   Rocky    3_Months      ML     77
6    Jony    6_Months  Python     62
7    Anil    6_Months  Python     63
8   Sunil    6_Months     SQL     42
9    Jony    6_Months     SQL     67
10   Anil    6_Months      ML     89
11  Rocky    6_Months      ML     81

In [25]:
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Exam_Months, Subject, score]
Index: []

In [21]:
# Syntax :- 
# dataframe.drop_duplicates([col_names],inplace = True/False)

In [22]:
df.drop_duplicates(["Name"])

    Name Exam_Months Subject  score
0   Jony    3_Months  Python     62
1   Anil    3_Months  Python     47
2  Sunil    3_Months     SQL     42
5  Rocky    3_Months      ML     77

## Handling Nulll Value

In [26]:
# creating Nan value = np.nan

In [27]:
# nan --> np.nan

In [28]:
# Empty values willl replace with nan

In [30]:
data = pd.read_csv("/Users/vijaypatil/Desktop/Innomatics/EDA/datasets/basic_info_missingdata.csv")
data

     Age  Weight (in kg)  Height (in m)
0   45.0            60.0           1.35
1   12.0            43.0           1.21
2   54.0            78.0           1.50
3   26.0            65.0           1.21
4   68.0            50.0           1.32
5   21.0             NaN           1.52
6   10.0            32.0           1.65
7   57.0            34.0           1.61
8   75.0            23.0           1.24
9   32.0            21.0           1.52
10  23.0             NaN           1.50
11  34.0            65.0           1.76
12  55.0            89.0           1.65
13  23.0            45.0           1.75
14  56.0            76.0           1.69
15  67.0            78.0           1.85
16  26.0            65.0           1.21
17  56.0            74.0           1.69
18  67.0            78.0            NaN
19  26.0            65.0           1.21
20  68.0            50.0           1.32
21   NaN            76.0           1.69
22  67.0            78.0           1.85

In [31]:
# isnull()

In [32]:
data.isnull()

      Age  Weight (in kg)  Height (in m)
0   False           False          False
1   False           False          False
2   False           False          False
3   False           False          False
4   False           False          False
5   False            True          False
6   False           False          False
7   False           False          False
8   False           False          False
9   False           False          False
10  False            True          False
11  False           False          False
12  False           False          False
13  False           False          False
14  False           False          False
15  False           False          False
16  False           False          False
17  False           False          False
18  False           False           True
19  False           False          False
20  False           False          False
21   True           False          False
22  False           False          False

In [33]:
data.isnull().sum()

Age               1
Weight (in kg)    2
Height (in m)     1
dtype: int64

In [ ]:
data.dropna()

     Age  Weight (in kg)  Height (in m)
0   45.0            60.0           1.35
1   12.0            43.0           1.21
2   54.0            78.0           1.50
3   26.0            65.0           1.21
4   68.0            50.0           1.32
6   10.0            32.0           1.65
7   57.0            34.0           1.61
8   75.0            23.0           1.24
9   32.0            21.0           1.52
11  34.0            65.0           1.76
12  55.0            89.0           1.65
13  23.0            45.0           1.75
14  56.0            76.0           1.69
15  67.0            78.0           1.85
16  26.0            65.0           1.21
17  56.0            74.0           1.69
19  26.0            65.0           1.21
20  68.0            50.0           1.32
22  67.0            78.0           1.85

In [37]:
data.dropna().isnull()

      Age  Weight (in kg)  Height (in m)
0   False           False          False
1   False           False          False
2   False           False          False
3   False           False          False
4   False           False          False
6   False           False          False
7   False           False          False
8   False           False          False
9   False           False          False
11  False           False          False
12  False           False          False
13  False           False          False
14  False           False          False
15  False           False          False
16  False           False          False
17  False           False          False
19  False           False          False
20  False           False          False
22  False           False          False

In [38]:
data.dropna().isnull().sum()

Age               0
Weight (in kg)    0
Height (in m)     0
dtype: int64

## Iterating through DataFrame

In [39]:
data = pd.read_csv("/Users/vijaypatil/Desktop/Innomatics/EDA/datasets/Input.csv")
data

    Empid     Name      Dept Gender     City  Salary
0       1   Samuel     Admin      M  Chennai   45000
1       2    Jerry        IT      M    Blore   75000
2       3  Michale     Sales      F      Goa   30000
3       4    Joann        IT      F  Chennai   80000
4       5   Sherin        IT      F    Blore   78000
5       6  Maxwell  Networks      M  Chennai   35000
6       7     John     Sales      M  Chennai   28000
7       8     Cruz        IT      M  Chennai   89000
8       9     Mary        IT      F    Blore   65000
9      10    Merry     Sales      F    Blore   45000
10     11    Jacob        IT      M      Goa   67000
11     12      Liz        IT      F  Kolkata   65000
12     13  Saneeta  Networks      F  Kolkata   55000
13     14    Jason     Sales      M      Goa   40000
14     15     Mike        IT      M  Kolkata    8000

In [40]:
for value in data["Salary"]:
               print("Salary :",value)

Salary : 45000
Salary : 75000
Salary : 30000
Salary : 80000
Salary : 78000
Salary : 35000
Salary : 28000
Salary : 89000
Salary : 65000
Salary : 45000
Salary : 67000
Salary : 65000
Salary : 55000
Salary : 40000
Salary : 8000

In [43]:
for index,values in data.iterrows():
               print("Index :",index)
               print("value :",values)
               print("_"*20)

Index : 0
value : Empid           1
Name       Samuel
Dept        Admin
Gender          M
City      Chennai
Salary      45000
Name: 0, dtype: object
____________________
Index : 1
value : Empid         2
Name      Jerry
Dept         IT
Gender        M
City      Blore
Salary    75000
Name: 1, dtype: object
____________________
Index : 2
value : Empid           3
Name      Michale
Dept        Sales
Gender          F
City          Goa
Salary      30000
Name: 2, dtype: object
____________________
Index : 3
value : Empid           4
Name        Joann
Dept           IT
Gender          F
City      Chennai
Salary      80000
Name: 3, dtype: object
____________________
Index : 4
value : Empid          5
Name      Sherin
Dept          IT
Gender         F
City       Blore
Salary     78000
Name: 4, dtype: object
____________________
Index : 5
value : Empid            6
Name       Maxwell
Dept      Networks
Gender           M
City       Chennai
Salary       35000
Name: 5, dtype: object
____________________
Index : 6
value : Empid           7
Name         John
Dept        Sales
Gender          M
City      Chennai
Salary      28000
Name: 6, dtype: object
____________________
Index : 7
value : Empid           8
Name         Cruz
Dept           IT
Gender          M
City      Chennai
Salary      89000
Name: 7, dtype: object
____________________
Index : 8
value : Empid         9
Name       Mary
Dept         IT
Gender        F
City      Blore
Salary    65000
Name: 8, dtype: object
____________________
Index : 9
value : Empid        10
Name      Merry
Dept      Sales
Gender        F
City      Blore
Salary    45000
Name: 9, dtype: object
____________________
Index : 10
value : Empid        11
Name      Jacob
Dept         IT
Gender        M
City        Goa
Salary    67000
Name: 10, dtype: object
____________________
Index : 11
value : Empid          12
Name          Liz
Dept           IT
Gender          F
City      Kolkata
Salary      65000
Name: 11, dtype: object
____________________
Index : 12
value : Empid           13
Name       Saneeta
Dept      Networks
Gender           F
City       Kolkata
Salary       55000
Name: 12, dtype: object
____________________
Index : 13
value : Empid        14
Name      Jason
Dept      Sales
Gender        M
City        Goa
Salary    40000
Name: 13, dtype: object
____________________
Index : 14
value : Empid          15
Name         Mike
Dept           IT
Gender          M
City      Kolkata
Salary       8000
Name: 14, dtype: object
____________________

In [ ]:
# for ind,val in dataset_name.iterrows():

In [ ]:
# data = pd.read_csv('Input.csv')
# data

## Apply

In [44]:
# Applying a fun on a particular column

In [ ]:
# Syntax :-
# df[colname].apply(functionname) # Display the count

In [45]:
data

    Empid     Name      Dept Gender     City  Salary
0       1   Samuel     Admin      M  Chennai   45000
1       2    Jerry        IT      M    Blore   75000
2       3  Michale     Sales      F      Goa   30000
3       4    Joann        IT      F  Chennai   80000
4       5   Sherin        IT      F    Blore   78000
5       6  Maxwell  Networks      M  Chennai   35000
6       7     John     Sales      M  Chennai   28000
7       8     Cruz        IT      M  Chennai   89000
8       9     Mary        IT      F    Blore   65000
9      10    Merry     Sales      F    Blore   45000
10     11    Jacob        IT      M      Goa   67000
11     12      Liz        IT      F  Kolkata   65000
12     13  Saneeta  Networks      F  Kolkata   55000
13     14    Jason     Sales      M      Goa   40000
14     15     Mike        IT      M  Kolkata    8000

In [46]:
def salary(x):
               if x>45000:
                              return "High"
               else:
                              return "Low"

In [49]:
data["Performance "] = data["Salary"].apply(salary)
data

    Empid     Name      Dept Gender     City  Salary Performance
0       1   Samuel     Admin      M  Chennai   45000          Low
1       2    Jerry        IT      M    Blore   75000         High
2       3  Michale     Sales      F      Goa   30000          Low
3       4    Joann        IT      F  Chennai   80000         High
4       5   Sherin        IT      F    Blore   78000         High
5       6  Maxwell  Networks      M  Chennai   35000          Low
6       7     John     Sales      M  Chennai   28000          Low
7       8     Cruz        IT      M  Chennai   89000         High
8       9     Mary        IT      F    Blore   65000         High
9      10    Merry     Sales      F    Blore   45000          Low
10     11    Jacob        IT      M      Goa   67000         High
11     12      Liz        IT      F  Kolkata   65000         High
12     13  Saneeta  Networks      F  Kolkata   55000         High
13     14    Jason     Sales      M      Goa   40000          Low
14     15     Mike        IT      M  Kolkata    8000          Low

In [61]:
def Annual_salary(x):
               return x*12

In [62]:
data["Annual salary "] = data["Salary"].apply(Annual_salary)
data

,Empid,Name,Dept,Gender,City,Salary,Performance,Annual salary
0,1,Samuel,Admin,M,Chennai,45000,Low,540000
1,2,Jerry,IT,M,Blore,75000,High,900000
2,3,Michale,Sales,F,Goa,30000,Low,360000
3,4,Joann,IT,F,Chennai,80000,High,960000
4,5,Sherin,IT,F,Blore,78000,High,936000
5,6,Maxwell,Networks,M,Chennai,35000,Low,420000
6,7,John,Sales,M,Chennai,28000,Low,336000
7,8,Cruz,IT,M,Chennai,89000,High,1068000
8,9,Mary,IT,F,Blore,65000,High,780000
9,10,Merry,Sales,F,Blore,45000,Low,540000
10,11,Jacob,IT,M,Goa,67000,High,804000
11,12,Liz,IT,F,Kolkata,65000,High,780000
12,13,Saneeta,Networks,F,Kolkata,55000,High,660000
13,14,Jason,Sales,M,Goa,40000,Low,480000
14,15,Mike,IT,M,Kolkata,8000,Low,96000

In [50]:
iris = pd.read_json("/Users/vijaypatil/Desktop/Innomatics/EDA/datasets/iris.json")
iris

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [ ]:
import math
def logo(x):
               return math.log(x)

In [59]:
iris["log_sepallength"] = iris["sepalLength"].apply(logo)
iris

,sepalLength,sepalWidth,petalLength,petalWidth,species,log_sepallength
0,5.1,3.5,1.4,0.2,setosa,1.629241
1,4.9,3.0,1.4,0.2,setosa,1.589235
2,4.7,3.2,1.3,0.2,setosa,1.547563
3,4.6,3.1,1.5,0.2,setosa,1.526056
4,5.0,3.6,1.4,0.2,setosa,1.609438
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,1.902108
146,6.3,2.5,5.0,1.9,virginica,1.840550
147,6.5,3.0,5.2,2.0,virginica,1.871802
148,6.2,3.4,5.4,2.3,virginica,1.824549
149,5.9,3.0,5.1,1.8,virginica,1.774952

In [56]:
import math

def logo(x):
    return math.log(x)

iris["log_sepallength"] = iris["sepalLength"].apply(logo)

iris

,sepalLength,sepalWidth,petalLength,petalWidth,species,log_sepallength
0,5.1,3.5,1.4,0.2,setosa,1.629241
1,4.9,3.0,1.4,0.2,setosa,1.589235
2,4.7,3.2,1.3,0.2,setosa,1.547563
3,4.6,3.1,1.5,0.2,setosa,1.526056
4,5.0,3.6,1.4,0.2,setosa,1.609438
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,1.902108
146,6.3,2.5,5.0,1.9,virginica,1.840550
147,6.5,3.0,5.2,2.0,virginica,1.871802
148,6.2,3.4,5.4,2.3,virginica,1.824549
149,5.9,3.0,5.1,1.8,virginica,1.774952

## Saving files

In [57]:
# Syntax :- 
# dataframe.to_csv('filepath with filename with extension')
# dataframe.to.json('filepath with filename with extension')

In [58]:
iris.to_csv("iris_new.csv")

## concatenate

In [63]:
# Syntax:
# pd.concat(list/tuple of dataframe,axxis=0/1)

In [64]:
# vertical concatenation (axis =0)

# for vertical concatenation column names should be same

In [65]:
Table1 = pd.DataFrame({'A': ['10', '11', '12', '13'],

                    'B': ['20', '21', '22', '23'],

                    'C': ['30', '31', '32', '33'],

                    'D': ['40', '41', '42', '43']})

Table2 = pd.DataFrame({'A': ['14', '15', '16', '17'],

                    'B': ['24', '25', '26', '27'],

                    'C': ['34', '35', '36', '37'],

                    'D': ['44', '45', '46', '47']},

                    index=[4, 5, 6, 7])

In [66]:
Table1

    A   B   C   D
0  10  20  30  40
1  11  21  31  41
2  12  22  32  42
3  13  23  33  43

In [67]:
Table2

    A   B   C   D
4  14  24  34  44
5  15  25  35  45
6  16  26  36  46
7  17  27  37  47

In [68]:
pd.concat([Table1,Table2],axis =0)

    A   B   C   D
0  10  20  30  40
1  11  21  31  41
2  12  22  32  42
3  13  23  33  43
4  14  24  34  44
5  15  25  35  45
6  16  26  36  46
7  17  27  37  47

In [73]:
# horizontal concatenation (axis=1)

# Index value should be same

In [69]:
Table1 = pd.DataFrame({'A': ['10', '11', '12', '13'],

                    'B': ['20', '21', '22', '23'],

                    'C': ['30', '31', '32', '33'],

                    'D': ['40', '41', '42', '43']})

Table2 = pd.DataFrame({'E': ['14', '15', '16', '17'],

                    'F': ['24', '25', '26', '27'],

                    'G': ['34', '35', '36', '37'],

                    'H': ['44', '45', '46', '47']})




Table1

    A   B   C   D
0  10  20  30  40
1  11  21  31  41
2  12  22  32  42
3  13  23  33  43

In [70]:
Table2

    E   F   G   H
0  14  24  34  44
1  15  25  35  45
2  16  26  36  46
3  17  27  37  47

In [71]:
pd.concat([Table1,Table2],axis=1)

    A   B   C   D   E   F   G   H
0  10  20  30  40  14  24  34  44
1  11  21  31  41  15  25  35  45
2  12  22  32  42  16  26  36  46
3  13  23  33  43  17  27  37  47

## Merge

In [74]:
left_frame = pd.DataFrame({'key': range(5), 

                           'left_value': ['a', 'b', 'c', 'd', 'e']})

left_frame

   key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e

In [75]:
right_frame = pd.DataFrame({'key': range(2, 7), 

                           'right_value': ['f', 'g', 'h', 'i', 'j']})

right_frame

   key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j

In [76]:
# Syntax :-
# pd.merge(df1,df2,on='colname on which merge happen',how='type of joins')

In [77]:
# Inner join :- common values

pd.merge(left_frame,right_frame,on="key",how="inner")

   key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h

In [ ]:
# outer join :- different values

pd.merge(left_frame,right_frame,on="key",how="outer")

   key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h
5    5        NaN           i
6    6        NaN           j

In [81]:
# Right join

pd.merge(left_frame,right_frame,on="key",how="right")

   key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h
3    5        NaN           i
4    6        NaN           j

In [80]:
# Left join

pd.merge(left_frame,right_frame,on="key",how="left")

   key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h