In [5]:
import pandas as pd
sales=pd.read_csv('https://raw.githubusercontent.com/tkseneee/Dataset/master/k_circle_sales.csv')

In [2]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Profit
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8,OUT049,1999,Medium,Tier 2,Supermarket Type1,3735.1380,11.5
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.3,OUT018,2009,Medium,Tier 2,Supermarket Type2,443.4228,14.3
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6,OUT049,1999,Medium,Tier 2,Supermarket Type1,2097.2700,14.5
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.1,OUT010,1998,NaN,NaN,Grocery Store,732.3800,13.6
4,NCD19,8.930,Low Fat,0.000000,Household,53.9,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,14.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,14.1
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.2,OUT045,2002,NaN,NaN,Supermarket Type1,549.2850,14.2
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1,OUT035,2004,Small,Tier1,Supermarket Type1,1193.1136,9.5
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1,OUT018,2009,Medium,Tier 2,Supermarket Type2,1845.5976,14.2
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.5,OUT046,1997,Small,Tier1,Supermarket Type1,765.6700,14.6

In [3]:
sales["Profit_Category"] = pd.cut(
    sales["Profit"],
    bins=[0, 10, 12, 14, 16],
    labels=["Low", "Medium", "High", "Very High"]
)

In [4]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Profit,Profit_Category
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8,OUT049,1999,Medium,Tier 2,Supermarket Type1,3735.1380,11.5,Medium
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.3,OUT018,2009,Medium,Tier 2,Supermarket Type2,443.4228,14.3,Very High
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6,OUT049,1999,Medium,Tier 2,Supermarket Type1,2097.2700,14.5,Very High
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.1,OUT010,1998,NaN,NaN,Grocery Store,732.3800,13.6,High
4,NCD19,8.930,Low Fat,0.000000,Household,53.9,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,14.1,Very High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,14.1,Very High
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.2,OUT045,2002,NaN,NaN,Supermarket Type1,549.2850,14.2,Very High
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1,OUT035,2004,Small,Tier1,Supermarket Type1,1193.1136,9.5,Low
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1,OUT018,2009,Medium,Tier 2,Supermarket Type2,1845.5976,14.2,Very High
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.5,OUT046,1997,Small,Tier1,Supermarket Type1,765.6700,14.6,Very High

In [7]:
sales["MRP_Visibility"] = (sales["Item_MRP"] * sales["Item_Visibility"]).round()

In [8]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Profit,Profit_Category,MRP_Visibility
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8,OUT049,1999,Medium,Tier 2,Supermarket Type1,3735.1380,11.5,Medium,4.0
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.3,OUT018,2009,Medium,Tier 2,Supermarket Type2,443.4228,14.3,Very High,1.0
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6,OUT049,1999,Medium,Tier 2,Supermarket Type1,2097.2700,14.5,Very High,2.0
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.1,OUT010,1998,NaN,NaN,Grocery Store,732.3800,13.6,High,0.0
4,NCD19,8.930,Low Fat,0.000000,Household,53.9,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,14.1,Very High,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,14.1,Very High,12.0
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.2,OUT045,2002,NaN,NaN,Supermarket Type1,549.2850,14.2,Very High,5.0
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1,OUT035,2004,Small,Tier1,Supermarket Type1,1193.1136,9.5,Low,3.0
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1,OUT018,2009,Medium,Tier 2,Supermarket Type2,1845.5976,14.2,Very High,15.0
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.5,OUT046,1997,Small,Tier1,Supermarket Type1,765.6700,14.6,Very High,3.0

In [9]:
sales["Sales_Performance"] = pd.qcut(
    sales["Item_Outlet_Sales"],
    q=4,
    labels=["Poor", "Average", "Good", "Excellent"]
)

In [10]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Profit,Profit_Category,MRP_Visibility,Sales_Performance
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8,OUT049,1999,Medium,Tier 2,Supermarket Type1,3735.1380,11.5,Medium,4.0,Excellent
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.3,OUT018,2009,Medium,Tier 2,Supermarket Type2,443.4228,14.3,Very High,1.0,Poor
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6,OUT049,1999,Medium,Tier 2,Supermarket Type1,2097.2700,14.5,Very High,2.0,Good
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.1,OUT010,1998,NaN,NaN,Grocery Store,732.3800,13.6,High,0.0,Poor
4,NCD19,8.930,Low Fat,0.000000,Household,53.9,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,14.1,Very High,0.0,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,14.1,Very High,12.0,Good
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.2,OUT045,2002,NaN,NaN,Supermarket Type1,549.2850,14.2,Very High,5.0,Poor
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1,OUT035,2004,Small,Tier1,Supermarket Type1,1193.1136,9.5,Low,3.0,Average
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1,OUT018,2009,Medium,Tier 2,Supermarket Type2,1845.5976,14.2,Very High,15.0,Good
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.5,OUT046,1997,Small,Tier1,Supermarket Type1,765.6700,14.6,Very High,3.0,Poor

In [2]:
import numpy as np
age = np.array([6,5,4,3,2,6,5,100])
age.mean()

np.float64(16.375)

In [3]:
from scipy import stats

age.sort()
stats.trim_mean(age,proportiontocut=0.2)

np.float64(4.833333333333333)

In [6]:
cat_data = sales.select_dtypes(include='object')
num_data = sales.select_dtypes(exclude='object')

/var/folders/fm/t_0d_0s533j69c8m_k2xl4300000gn/T/ipykernel_12231/252833833.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_data = sales.select_dtypes(include='object')

In [7]:
propcut = stats.trim_mean(num_data,proportiontocut=.10)
result=pd.DataFrame()

result['mean']=num_data.mean()
result['median']=num_data.median()
result['trim_mean']=propcut
result

                                  mean       median    trim_mean
Item_Weight                  11.676740    11.800000          NaN
Item_Visibility               0.066132     0.053931     0.060344
Item_MRP                    140.998838   142.700000   139.706731
Outlet_Establishment_Year  1997.831867  1999.000000  1998.039742
Item_Outlet_Sales          2181.288914  1794.331000  1971.326788
Profit                       13.414514    13.900000    13.744640

In [8]:
num_data.quantile(.25)

Item_Weight                     7.720000
Item_Visibility                 0.026989
Item_MRP                       93.800000
Outlet_Establishment_Year    1987.000000
Item_Outlet_Sales             834.247400
Profit                         13.150000
Name: 0.25, dtype: float64

In [10]:
num_data['Item_Outlet_Sales'].quantile(.25)

# the 25% sell happened under 834
# the 75% sell happened above 834

np.float64(834.2474)

In [13]:
num_data['Profit'].quantile(.04)

# 4% of the data under 10% profit

np.float64(10.0)

In [ ]:
# mode :- is useful for category data

In [15]:
# measure of dispersion
# range
# iqr
# variance
# standard deviation
# coeff of variance

In [16]:
stock_A_return = 30
stock_A_volatality = 20

In [17]:
stock_B_return = 25
stock_B_volatality = 15

In [ ]:
# range = difference between highest and the lowest value

num_data["Item_Outlet_Sales"].max()-num_data['Item_Outlet_Sales'].min()

# influenced by the outliers

np.float64(13053.674799999999)

In [22]:
# IQR = Inter quartile range
# IQR = Q3-Q1

num_data['Item_Outlet_Sales'].quantile(.75)-num_data['Item_Outlet_Sales'].quantile(.25)

np.float64(2267.049)

In [24]:
# variance = sum of the data(xi - x bar)**2/total no of values
num_data.var().round()

Item_Weight                       33.0
Item_Visibility                    0.0
Item_MRP                        3876.0
Outlet_Establishment_Year         70.0
Item_Outlet_Sales            2912141.0
Profit                             3.0
dtype: float64

In [25]:
# Standard deviation = Square root of the variance

num_data.std().round()

Item_Weight                     6.0
Item_Visibility                 0.0
Item_MRP                       62.0
Outlet_Establishment_Year       8.0
Item_Outlet_Sales            1706.0
Profit                          2.0
dtype: float64

In [28]:
# correlation of variation

# std/mean

(num_data.std()/num_data.mean())

Item_Weight                  0.494732
Item_Visibility              0.780224
Item_MRP                     0.441550
Outlet_Establishment_Year    0.004190
Item_Outlet_Sales            0.782335
Profit                       0.126866
dtype: float64